### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by buluma**
corrected typos

### CODE REVIEW

**Comment by drybjed** [comment]
Thanks! README.md is generated by [ansigenome](https://github.com/nickjj/ansigenome/) so you should update the synopsis part in `meta/ansigenome.yml` as well so the changes are not lost on an update.

**Comment by buluma** [comment]
Right on :) I missed that.

**Comment by drybjed** [comment]
@buluma OK, so you need to push an update to your fork. :-)

**Comment by ypid** [comment]
@drybjed Sometimes it could be more productive to merge and fix it yourself :-) All those comments for one spelling fix. Especially when there are timezone shifts ;-)

**Comment by drybjed** [comment]
@ypid Yeah, I guess I can merge it as is then. :-)

**Comment by ypid** [comment]
@drybjed Turns out I already fixed the typo in `meta/ansigenome.yml`. I think it will be best when you run ansigenome more regularly? I will give you a hint when I change something there again. Or I will need to setup ansigenome for the DebOps project (I guess I will have to do that some day anyway).

**Pull request merged**
