### PR TITLE
Fixed template lookup syntax

### PR DESCRIPTION
**Pull request by jstruebel**

### CODE REVIEW

**Comment by drybjed** [comment]
The `template` and `template_src` modules aren't equivalent. What are you trying to do?

**Comment by jstruebel** [comment]
When I tried to run a play that included the role, I got an error that it couldn't find the stat_home_path.j2 file because it was looking for it under the files directory instead of the templates directory. I compared the lookup command with one of the other roles that worked for me and saw that it used template_src so I made the change and then it worked.

I am still using ansible v1.9.4, is this something that's changed for newer versions?

**Comment by drybjed** [comment]
That explains it. Ansible 1.9.x used to look for templates in `lookup("template")` in the `files/` directory, Ansible v2 looks for them in the `templates/` directory. There are also more changes between Ansible 1.9 and v2, you should consider upgrading. I try to keep DebOps compatible with current stable Ansible version, which at the moment is2.1 Older versions might not work at some point due to changes in Ansible - this being one of them.

**Comment by jstruebel** [comment]
Ok, I'll look into upgrading my installation.

**Pull request closed without merging**
